# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161004_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='img/avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
