# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 18:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('content_es', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
